name: Donatello
description: Il laboratorio digitale per idee regalo uniche
publish_to: 'none'
version: 1.0.2+3

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  
  # State management
  flutter_riverpod: ^2.4.9
  
  # Navigation
  go_router: ^12.1.1
  
  # HTTP and API
  dio: ^5.3.4
  
  # Storage
  flutter_secure_storage: ^9.0.0
  shared_preferences: ^2.2.2
  
  # UI and Fonts
  google_fonts: ^6.1.0
  cached_network_image: ^3.3.0
  
  # Utilities
  equatable: ^2.0.5
  json_annotation: ^4.9.0
  intl: ^0.20.2
  url_launcher: ^6.2.2
  webview_flutter: ^4.4.4

  flutter_svg: ^1.1.6
  
  #sentry for error tracking
  sentry_flutter: ^8.14.2

  # Firebase
  firebase_analytics: ^10.8.0
  firebase_core: ^2.24.2

  cupertino_icons: ^1.0.2

  share_plus: ^11.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.4.7
  json_serializable: ^6.7.1
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"

  
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/auth/
    - assets/images/relations/
    - assets/images/categories/
    - assets/images/logos/

  generate: true