// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // Configurazione Android 
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnLZRLrlD5k-RxnIiWRlVRk9II9AVU80U',
    appId: '1:991315820441:android:your-android-app-id',
    messagingSenderId: '991315820441',
    projectId: 'donatello-lab',
    storageBucket: 'donatello-lab.firebasestorage.app',
  );

  // Configurazione iOS
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnLZRLrlD5k-RxnIiWRlVRk9II9AVU80U',
    appId: '1:991315820441:ios:b8d57f51486e69d4191d08',
    messagingSenderId: '991315820441',
    projectId: 'donatello-lab',
    storageBucket: 'donatello-lab.firebasestorage.app',
    iosBundleId: 'com.simonediaco.donatellolab',
  );

  // Configurazione Web
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnLZRLrlD5k-RxnIiWRlVRk9II9AVU80U',
    appId: '1:991315820441:web:ceaa9afb43343c3b191d08',
    messagingSenderId: '991315820441',
    projectId: 'donatello-lab',
    storageBucket: 'donatello-lab.firebasestorage.app',
  );
}